name: Ares
description: Plugin for managing duels, group fights and tournaments
author: Moros
version: ${pluginVersion}
main: me.moros.ares.Ares
softdepend: [ProjectKorra, Bending, Gaia]
api-version: 1.18
